# Generated by Cursor on 2026-05-16

from django.db import migrations, models
from django.utils import timezone


def copy_old_citations_to_quote(apps, schema_editor):
    ResearchSummary = apps.get_model("research", "ResearchSummary")
    for s in ResearchSummary.objects.all().only("id", "citation_quote"):
        # The old field is still present at this point in the migration.
        old = getattr(s, "citations", "") or ""
        if not (s.citation_quote or "").strip() and old.strip():
            s.citation_quote = old
            s.save(update_fields=["citation_quote"])


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="researchproject",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("on_hold", "On hold"), ("completed", "Completed")],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resource",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="researchsummary",
            name="citation_source",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="researchsummary",
            name="citation_page",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="researchsummary",
            name="citation_quote",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="researchsummary",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="researchsummary",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(copy_old_citations_to_quote, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="researchsummary",
            name="citations",
        ),
        migrations.AddField(
            model_name="comparisontable",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="comparisontable",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comparisontable",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comparisonrow",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="comparisonrow",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comparisonrow",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
    ]

